### ISSUE TITLE
Configuring two httpmodules generated two identical requests

### ISSUE THREAD

**Issue by SergeyKanzhelev** [Microsoft/ApplicationInsights-server-dotnet#26] opened 2016-02-11 18:43 UTC
HttpModule should use a singleton to generate Begin and End ETW events so we will not send duplicates when misconfigured

**Comment by abaranch** [comment] 2016-03-01 19:03
We cannot reliably detect if you have identical modules defined in the config, or IIS creats several HttpApplication instances: http://erraticdev.blogspot.com/2011/01/how-to-correctly-use-ihttpmodule-to.html 
@SergeyKanzhelev Let's close this by design.

**Comment by SergeyKanzhelev** [comment] 2016-03-01 22:54
As discussed offline we may want to try to detect dups inside a single request.

**Closed** 2016-03-02 22:26 UTC
Labels: bug, p3
